### ISSUE TITLE
Payment service response refactor

### ISSUE THREAD

**Issue by shan4488** [GGAshwin/Hotel-Booking-API#3]
Please give me the payment response as follows:
{
 paymentId: String
 paymentStatus: Enum ( PENDING, CONFIRMED, CANCELLED)
}

**Comment by GGAshwin** [comment]
There is currently an api with the endpoint 
/payments/:payment_id/status

which returns
{
    payment_id: string,
    status: Enum ( PENDING, CONFIRMED, CANCELLED)
}

**Comment by shan4488** [comment]
Hi GG,

I feel that this endpoint doesn't help me much. Because to call this api endpoint, I need the payment id which I should get from your payment endpoint. But it's okay, I will create a dto related to your payment endpoint and I will only take the required field from your response. If any other requirement is there, I will ping you!

Thanks

Regards,
Sharan Kumar
